### ISSUE TITLE
Transactional token being ignored

### ISSUE THREAD

**Issue by lukejpreston** [52North/SOS#650]
This is my `docker-compose.yaml` file

```yaml
version: '3'
services:
  sos-service:
    image:  52north/sos:4.4.6
    ports:
      - 5050:8080
```

I am using it for local development. I have checked `Transactional security active` and put in my valid IP Address, I have set the token to some random string using pythons `secrets.token_hex`. It seems so long as the `Authorization` header is present it is valid request on the same IP regardless of what the token actually is.

This doesn't feel like it should be correct behaviour.
